### PR TITLE
Added participant page for Santhosh

### LINKED ISSUE #19: Add Santhosh to the list of workshop participants
There should be a page at the route/participants/san that has my name, a picture, and some information about me. This page should also be linked to the site's homepage.

### PR DESCRIPTION
**Pull request by sbappan**
Fixes #19

### CODE REVIEW

**Comment by egiurleo** [comment]
Thanks so much for the contribution, @sbappan! Could you remove package-lock.json from your PR? You can do that using the following command: `git rm --cached package-lock.json` and then pushing again.

**Comment by sbappan** [comment]
Was wondering how to do that. Removed the file and pushed again. Thanks for the great workshop!

**Comment by egiurleo** [comment]
Thanks for attending the workshop, @sbappan! Great job on this PR!

**Comment by sbappan** [comment]
Fantastic. Thanks again!

**Pull request merged**
